(lang dune 3.10)
(name qpa)
(generate_opam_files false)
(package
 (name qpa)
 (synopsis "QPA intraday backtest experiments")
 (description "Modularized version of strategy_fast backtest using Core and dune"))
