val tick_size : float
val tick_value : float
val be_trigger_mult : float
val b2_downgrade_grace_min : int
val twoR_range_cutoff_mult : float
val abr_range_cap_mult : float
val gap_pct_low : float
val gap_pct_high : float
val body_pct_min : float
val ibs_bull_min : float
val ibs_bear_max : float
val entry_slip_ticks : float
